CLASS zcl_log_ej DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .
  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LOG_EJ IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.
    out->write( TEXT-001 ).
  ENDMETHOD.
ENDCLASS.
